INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Bake Something", -10);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Cuddle up next to the fireplace", -9);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Play a game of Jenga", -8);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Play some Monopoly", -7);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Play some Catan", -6);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Builf a snowfort", -5);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Go ice fishing", -4);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Make hot chocolate", -3);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Watch a scary movie!", -2);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Read your favorite book", -1);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Take a spa day", 0);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Art Day", 1);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Create something new", 2);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Watch LOTR", 3);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Watch Harry Potter", 4);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Make friendship bracelets", 5);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Go camping (bring a flannel)", 6);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Have a bonfire", 7);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("High five a friend", 8);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Text someone a compliment", 9);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Try a new video game", 10);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Achieve world domination", 11);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Go fishing", 12);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Walk through a park", 13);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Watch the sunrise", 14);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Go visit a new restaurant", 15);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Meet a friend for drinks", 16);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Lay out in the sun", 17);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Go to the beach", 18);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Find a yeti", 19);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Meander around target", 20);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("try to do some knitting", 21);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Make homemade pizza", 22);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Just order your favorite dish", 23);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Have a BBQ", 24);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Go for a hike", 25);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Tell someone you love them", 26);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Go to an amuesement park", 27);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Go garage saling", 28);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Watch the sunset", 29);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Make some brunch", 30);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Get an iced coffee", 31);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Do some gardening", 32);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Have a water fight.", 33);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Have a theme day, and dress and behave accordingly", 34);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Go on an adventure", 35);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Sing in the shower", 36);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Try face & finger painting", 37);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Turn on the AC", 38);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Become a mummy", 39);
INSERT INTO activities (ACTIVITY, TEMP) VALUES ("Burn because you're in hell", 40);
